from __future__ import annotations

from strategic_alpha_engine.domain.metadata_catalog import FieldMetadata, MetadataCatalog, OperatorMetadata
from strategic_alpha_engine.domain.enums import (
    FieldClass,
    OperatorCategory,
    OutlierRiskLevel,
    ResearchHorizon,
    UpdateCadence,
)


def load_seed_metadata_catalog() -> MetadataCatalog:
    return MetadataCatalog(
        fields=[
            FieldMetadata(
                field_id="close",
                field_class=FieldClass.PRICE,
                update_cadence=UpdateCadence.DAILY,
                description="Adjusted close price for liquid common equities.",
                recommended_horizons=[ResearchHorizon.SHORT, ResearchHorizon.MEDIUM, ResearchHorizon.LONG],
                discouraged_patterns=["raw_level_only"],
                safe_min_lookback_days=5,
                safe_max_lookback_days=252,
                normalization_recommendation="cross_sectional_rank",
                outlier_risk=OutlierRiskLevel.MEDIUM,
            ),
            FieldMetadata(
                field_id="volume",
                field_class=FieldClass.VOLUME,
                update_cadence=UpdateCadence.DAILY,
                description="Daily trading volume as a liquidity and confirmation proxy.",
                recommended_horizons=[ResearchHorizon.SHORT, ResearchHorizon.MEDIUM],
                discouraged_patterns=["unbounded_raw_volume"],
                safe_min_lookback_days=5,
                safe_max_lookback_days=126,
                normalization_recommendation="cross_sectional_rank",
                outlier_risk=OutlierRiskLevel.HIGH,
            ),
            FieldMetadata(
                field_id="cashflow_op",
                field_class=FieldClass.FUNDAMENTAL,
                update_cadence=UpdateCadence.QUARTERLY,
                description="Operating cashflow for detecting quality improvement or deterioration.",
                recommended_horizons=[ResearchHorizon.MEDIUM, ResearchHorizon.LONG],
                discouraged_patterns=["short_delay_on_slow_fundamentals", "raw_level_only"],
                safe_min_lookback_days=20,
                safe_max_lookback_days=252,
                normalization_recommendation="ratio_or_rank",
                outlier_risk=OutlierRiskLevel.MEDIUM,
            ),
            FieldMetadata(
                field_id="debt_lt",
                field_class=FieldClass.FUNDAMENTAL,
                update_cadence=UpdateCadence.QUARTERLY,
                description="Long-term debt level for leverage-related quality research.",
                recommended_horizons=[ResearchHorizon.MEDIUM, ResearchHorizon.LONG],
                discouraged_patterns=["short_delay_on_slow_fundamentals", "raw_level_only"],
                safe_min_lookback_days=20,
                safe_max_lookback_days=252,
                normalization_recommendation="denominator_floor_then_rank",
                outlier_risk=OutlierRiskLevel.HIGH,
            ),
            FieldMetadata(
                field_id="equity",
                field_class=FieldClass.FUNDAMENTAL,
                update_cadence=UpdateCadence.QUARTERLY,
                description="Book equity for value, leverage, and capital structure normalization.",
                recommended_horizons=[ResearchHorizon.MEDIUM, ResearchHorizon.LONG],
                discouraged_patterns=["short_sum_on_slow_fields"],
                safe_min_lookback_days=20,
                safe_max_lookback_days=252,
                normalization_recommendation="ratio_or_rank",
                outlier_risk=OutlierRiskLevel.MEDIUM,
            ),
            FieldMetadata(
                field_id="eps_estimate",
                field_class=FieldClass.ANALYST,
                update_cadence=UpdateCadence.WEEKLY,
                description="Consensus EPS estimate proxy for revision-drift research.",
                recommended_horizons=[ResearchHorizon.SHORT, ResearchHorizon.MEDIUM],
                discouraged_patterns=["raw_level_only"],
                safe_min_lookback_days=5,
                safe_max_lookback_days=126,
                normalization_recommendation="time_series_delta_then_rank",
                outlier_risk=OutlierRiskLevel.MEDIUM,
            ),
        ],
        operators=[
            OperatorMetadata(
                operator_id="rank",
                category=OperatorCategory.CROSS_SECTIONAL,
                min_arity=1,
                max_arity=1,
                requires_lookback=False,
                supports_constants=False,
                notes="Preferred final normalization for early-stage equity signals.",
            ),
            OperatorMetadata(
                operator_id="ts_delta",
                category=OperatorCategory.TIME_SERIES,
                min_arity=2,
                max_arity=2,
                requires_lookback=True,
                supports_constants=False,
                discouraged_for_cadences=[UpdateCadence.QUARTERLY, UpdateCadence.SLOW, UpdateCadence.IRREGULAR],
                notes="Use conservative lookbacks when applied to slow or sparse fields.",
            ),
            OperatorMetadata(
                operator_id="ts_std_dev",
                category=OperatorCategory.TIME_SERIES,
                min_arity=2,
                max_arity=2,
                requires_lookback=True,
                supports_constants=False,
                notes="Useful for volatility scaling on reasonably fast-updating series.",
            ),
            OperatorMetadata(
                operator_id="divide",
                category=OperatorCategory.ARITHMETIC,
                min_arity=2,
                max_arity=2,
                requires_lookback=False,
                supports_constants=True,
                notes="Safe when paired with denominator floors and final normalization.",
            ),
            OperatorMetadata(
                operator_id="subtract",
                category=OperatorCategory.ARITHMETIC,
                min_arity=2,
                max_arity=2,
                requires_lookback=False,
                supports_constants=False,
                notes="Simple spread construction for pairwise economic relationships.",
            ),
            OperatorMetadata(
                operator_id="abs",
                category=OperatorCategory.ARITHMETIC,
                min_arity=1,
                max_arity=1,
                requires_lookback=False,
                supports_constants=False,
                notes="Useful for denominator stabilization and guard rails.",
            ),
            OperatorMetadata(
                operator_id="ts_sum",
                category=OperatorCategory.TIME_SERIES,
                min_arity=2,
                max_arity=2,
                requires_lookback=True,
                supports_constants=False,
                discouraged_for_cadences=[UpdateCadence.QUARTERLY, UpdateCadence.SLOW, UpdateCadence.IRREGULAR],
                notes="Often pseudo-time-series on slow fields unless lookbacks are conservative.",
            ),
            OperatorMetadata(
                operator_id="group_backfill",
                category=OperatorCategory.CONTROL_FLOW,
                min_arity=2,
                max_arity=3,
                requires_lookback=False,
                supports_constants=False,
                notes="Keep out of early-stage candidate generation due to hidden data shaping risk.",
            ),
            OperatorMetadata(
                operator_id="trade_when",
                category=OperatorCategory.CONTROL_FLOW,
                min_arity=2,
                max_arity=3,
                requires_lookback=False,
                supports_constants=False,
                notes="Operationally powerful but intentionally excluded from early conservative synthesis.",
            ),
        ],
    )
